### ISSUE TITLE
Install Failing After commit 5728ba4  On Mac

### ISSUE THREAD

**Issue by davidkuep** [Kozea/Multicorn#122]
Hi all-

Had a heck of a time installing this using OSX 10.9.5 and 9.5beta2, lots of failing with:
```
src/query.c:662:16: error: too many arguments to function call, expected 8, have
      9
  ...NULL);
     ^~~~
/Volumes/Stripe/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include/stddef.h:77:16: note: 
      expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
/usr/local/Cellar/postgresql-9.5/9.5beta2/include/server/optimizer/pathnode.h:82:1: note: 
      'create_foreignscan_path' declared here
extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
^
1 error generated.
make: *** [src/query.o] Error 1
```
Reading back through a few old threads, found what might be the issue, seems that the last commit changed some lines looking for pg9.6 to looking for pg9.5, when I reverted to the previous commit (17ef31d) I was able to make without error. Hope that's helpful.

**Comment by rdunklau** [comment]
Thank you for the report.

The problem is, the API changed since 9.5 beta2. So the latest commit is "correct" in the sense that it is the API that will be shipped with 9.5.

Unfortunately, I can't maintain the compatibility with beta versions, since the "PG_VERSION_NUM" constant is equal to 90500 in both cases, whereas it is later incremented with stable minor versions.
